### ISSUE TITLE
sometimes it doesn't work?

### ISSUE THREAD

**Issue by citrusky** [Arechii/GroupLimiter#3]
Dear Arechii:
Thanks for the plugin, well done!
But I got one issue here.

I've added this plugin and set the max number as 4.
But there still a huge group playing on my server.
I've checked their profiles and it's all private.

I wonder if grouplimiter can't detect it when a player's profile is private.
Or does grouplimiter need an update after Nelson changed the system of in-game groups?

Thanks for your time and help.
Cheers.

**Comment by Arechii** [comment]
Hi there

I believe it currently only works on servers with Allow_Dynamic_Groups: false in their Config.json.
I will look into adding it for the new group system too. ;D

**Comment by citrusky** [comment]
Thanks for the reminding!
I'll try it right away.
Many thanks! : )

**Comment by citrusky** [comment]
Thanks for the help. The plugin runs fine on my servers. All good! : )
